config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :bands
  resources :albums
  resources :tracks 
end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :band

  has_many :tracks
  
end

app/models/band.rb
class Band < ActiveRecord::Base

  has_many :albums

  has_many :tracks,
  through: :albums,
  source: :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base

  belongs_to :album

  has_one :band,
  through: :album,
  source: :band

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    if user.is_password?(password)
      return user
    else
      nil 
    end
  end

  def reset_session_token!
    self.session_token=User.generate_session_token
    self.save
  end

  def ensure_session_token
    self.session_token||= User.generate_session_token
  end

  def password=(password)
    self.password_digest=BCrypt::Password.create(password)
  end

  def is_password?(password)
    pass = BCrypt::Password.new(self.password_digest)
    pass.is_password?(password)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :ensure_logged_in

  def new
    @band = Band.find_by(params[:id])
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    band_name = params[:band_name]
    band = Band.find_by(name: band_name)
    @album.band_id = band.id
    if @album.save
      redirect_to album_url(@album)
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def destroy
    render :show
  end

  def album_params
    params.require(:album).permit(:title, :band_id, :live)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method  :current_user, :current_band, :logged_in?, :login_user!, :ensure_logged_in

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login_user!(user)
    session[:session_token] = user[:session_token]
  end

  def logout_user!
    session[:session_token] = nil
  end

  def logged_in?
    if @current_user
      return true
    else
      nil
    end
  end

  def ensure_logged_in
    if @current_user.nil?
      redirect_to bands_url
    end
  end

  def current_band
    @current_band ||= Band.find_by_id(band[:id])
  end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  

  def index
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    end
  end

  def destroy
    render :index
  end

  def show
     @band = Band.find(params[:id])
     render :show
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user.nil?
      render :new
    else
      login_user!(user)
      redirect_to bands_url
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    @album = Album.find_by(params[:id])
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    album_title = params[:album_title]
    album = Album.find_by(title: album_title)
    @track.album_id = album.id

    if @track.save
      redirect_to track_url(@track)
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def destroy
    redirect_to bands_url
  end

  def track_params
    params.require(:track).permit(:title, :album_id, :bonus, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      :login_user!(@user)
      redirect_to bands_url
    else
      redirect_to users_url
    end
  end

  def show
    render :show
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input
    type='hidden'
    name='authenticity_token'
     value =#{form_authenticity_token} '>".html_safe
  end
  
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<form class="" action="/albums" method="post">
  <%= auth_token %>
  <label for="band_name"> Band Name</label> <br>
  <input type="text" name="band_name" value=""> <br>
  <label for="album_name"> Album Title </label> <br>
  <input type="text" name="album[title]" value=""><br>
  <label for="live_album"> Is is a live album? </label> <br>
  <input type="radio" name="album[live]" value="true"> Yes <br>
  <input type="radio" name="album[live]" value="false"> No <br>
  <button type="submit" name="button"> Create Album </button> <br> 
</form>

app/views/albums/show.html.erb
<h2> <%= @album.band.name %> </h2>
<br>

<h1> <%=@album.title %> </h1>
<br>
<ul>
<% @album.tracks.each do |track| %>
<li> <%= link_to track.title, track_url(track) %> </li>
<% end %>
</ul>
<%= link_to "Create New Track", new_track_url, {:id => @album.id }%> <br>
<%= link_to "Delete Album", album_url, {:id => @album.id, method: :delete}%> <br>
<%= link_to "Back to band", band_url(@album.band)%>

app/views/bands/index.html.erb
<h1> Welcome to MusicApp </h1>

<h2> All bands: </h2>

<% @bands = Band.all %>
<ul>
<% @bands.each do |band| %>
<li> <%= link_to band.name, band_url(band) %> </li>
  <% end %>
<ul>
<%= link_to "Create New Band", new_band_url%>

app/views/bands/new.html.erb
<form class="" action="/bands" method="post">
  <%= auth_token %>
  <label for="band_name"> Band Name</label>
  <input type="text" name="band[name]" value="">
  <button type="submit" name="button"> Create Band </button>
</form>

app/views/bands/show.html.erb
<h1> <%= @band.name %> <h1>
<br>
<br>
<h2> Albums <h2>
<br>
<ul>
<% @band.albums.each do |album| %>
<li> <%= link_to album.title, album_url(album) %> </li>
<% end %>
</ul>

<h2> Links <h2>
<%= link_to "Create New Album", new_album_url, {:id => @band.id }%> <br>
<%= link_to "Delete Band", band_url, {:id => @band.id, method: :delete}%> <br>
<%= link_to "Back to All Bands", bands_url%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if :logged_in? %>
    <%= button_to "Logout", session_url, method: :delete %>
  <%end %>
  <%= current_user.email %>


<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<form action="/session" method="post">
  <%= auth_token %>
  <label for="email">Email</label><br>
  <input type="text" name="user[email]"><br>
  <label for="Password">Password</label><br>
  <input type="password" name="user[password]"><br>
  <button type="submit"> Sign in!</button>
</form>

app/views/tracks/new.html.erb
<form class="" action="/tracks" method="post">
  <%= auth_token %>
  <label for="album_title"> Album Name</label> <br>
  <input type="text" name="album_title" value=""><br>
  <label for="album_name"> Track Title </label><br>
  <input type="text" name="track[title]" value=""><br>
  <label for="live_album"> Is is a bonus track? </label><br>
  <input type="radio" name="track[bonus]" value="true"> Yes <br>
  <input type="radio" name="track[bonus]" value="false"> No <br>
  <label for="track_lyrics">Lyrics</label><br>
  <textarea id="track_lyrics" name = "track[lyrics]"> </textarea> <br>
  <button type="submit" name="button"> Create Track </button>
</form>

app/views/tracks/show.html.erb
<h2> <%= @track.album.title %> </h2>
<br>

<h1> <%=@track.title %> </h1>
<br>
<ul>
<p> <%= @track.lyrics %><p>
  <br>
<%= link_to "Back to album", album_url(@track.album)%><br> 
<%= link_to "Delete Track", track_url, {:id => @track.id, method: :delete}%> <br>

app/views/users/index.html.erb
<%= current_user.email %>

app/views/users/new.html.erb
<form action="/users" method="post">
  <%= auth_token %>
  <label for="email">Email</label><br>
  <input type="text" name="user[email]"><br>
  <label for="Password">Password</label><br>
  <input type="password" name="user[password]"><br>
  <button type="submit"> Sign up!</button>
</form>

app/views/users/show.html.erb
<%= current_user.email if current_user%>